#!/usr/bin/env bash#!/usr/bin/env bash
echo "Listing objects..."

if [ -z $1 ]; then
    echo "No bucket name provided"
    exit 1
fi

aws s3api list-objects-v2 \
    --bucket $1 \
    --query Contents[].Key