#!/usr/bin/env bash

# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy.html

echo "deleting s3 bucket using cfn"
STACK_NAME="cfn-s3-simple"

aws cloudformation delete-stack \
--stack-name $STACK_NAME